# Generated by Django 3.1.7 on 2021-02-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting_text', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='slider_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200)),
                ('site_logo', models.ImageField(blank=True, upload_to='logos')),
                ('logo_text', models.CharField(blank=True, max_length=50)),
                ('favicon', models.ImageField(blank=True, upload_to='favicons')),
                ('cpy_text', models.CharField(blank=True, max_length=1000)),
                ('loader', models.CharField(choices=[('On', 'On'), ('Off', 'Off')], default='On', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Buttons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('status', models.CharField(blank=True, choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('light', 'light'), ('dark', 'dark')], max_length=20)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.herosection')),
            ],
        ),
    ]
