# Generated by Django 3.1.7 on 2021-02-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.PositiveIntegerField()),
                ('total_project', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='about')),
            ],
        ),
    ]
