# Generated by Django 3.1.7 on 2021-02-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.DateField()),
                ('ending_time', models.DateField()),
                ('title', models.CharField(max_length=25)),
                ('university', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=180)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
