# Generated by Django 3.1.7 on 2021-03-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_skillsection_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnableSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(choices=[('Show', 'Show'), ('Hide', 'Hide')], default='show', max_length=5)),
                ('resume', models.CharField(choices=[('Show', 'Show'), ('Hide', 'Hide')], default='Show', max_length=5)),
                ('service', models.CharField(choices=[('Show', 'Show'), ('Hide', 'Hide')], default='Show', max_length=5)),
                ('skill', models.CharField(choices=[('Show', 'Show'), ('Hide', 'Hide')], default='Show', max_length=5)),
                ('projects', models.CharField(choices=[('Show', 'Show'), ('Hide', 'Hide')], default='Show', max_length=5)),
                ('blog', models.CharField(choices=[('Show', 'Show'), ('Hide', 'Hide')], default='Show', max_length=5)),
                ('footer_section', models.CharField(choices=[('Show', 'Show'), ('Hide', 'Hide')], default='Show', max_length=5)),
                ('contact', models.CharField(choices=[('Show', 'Show'), ('Hide', 'Hide')], default='Show', max_length=5)),
            ],
        ),
    ]
