# Generated by Django 3.1.7 on 2021-03-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0008_auto_20210301_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='enablesections',
            name='loader',
            field=models.CharField(choices=[('Show', 'Show'), ('Hide', 'Hide')], default='Show', max_length=5),
        ),
    ]
