# Generated by Django 3.1.7 on 2021-03-03 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0011_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Projects'),
            preserve_default=False,
        ),
    ]
