# Generated by Django 3.1.7 on 2021-03-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0012_projects_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='live_link',
            field=models.URLField(blank=True),
        ),
    ]
